name: Mobile CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: ['mobile/**']
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd mobile
          npm ci
      - name: Run tests
        run: |
          cd mobile
          npm test
      - name: Build
        run: |
          cd mobile
          npx expo export